"""adding social case table

Revision ID: 63af805e04c1
Revises: 
Create Date: 2021-12-07 17:30:46.662062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63af805e04c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assistance_id', sa.Integer(), nullable=False),
    sa.Column('employee_rut', sa.String(length=12), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_names', sa.String(length=250), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('delegation', sa.String(length=120), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_case')
    # ### end Alembic commands ###
