"""adding closing status table

Revision ID: cb420a6c9178
Revises: ef56d7072cd8
Create Date: 2021-12-13 16:10:27.354853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb420a6c9178'
down_revision = 'ef56d7072cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_case_close',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('professional_names', sa.String(length=120), nullable=False),
    sa.Column('observations', sa.String(length=900), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('social_case', sa.Column('closing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'social_case', 'social_case_close', ['closing_id'], ['id'])
    op.create_unique_constraint(None, 'social_case_assistance', ['id'])
    op.create_unique_constraint(None, 'social_case_derivation', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_case_derivation', type_='unique')
    op.drop_constraint(None, 'social_case_assistance', type_='unique')
    op.drop_constraint(None, 'social_case', type_='foreignkey')
    op.drop_column('social_case', 'closing_id')
    op.drop_table('social_case_close')
    # ### end Alembic commands ###
