"""adding is_complete to intervention plan

Revision ID: e8aa52cc082e
Revises: cb420a6c9178
Create Date: 2021-12-14 14:19:24.986241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8aa52cc082e'
down_revision = 'cb420a6c9178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervention_plan', sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False))
    op.create_unique_constraint(None, 'social_case_close', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_case_close', type_='unique')
    op.drop_column('intervention_plan', 'is_completed')
    # ### end Alembic commands ###
