"""adding derivation and professional table

Revision ID: ef56d7072cd8
Revises: af570eb9b821
Create Date: 2021-12-13 14:46:58.107369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef56d7072cd8'
down_revision = 'af570eb9b821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_case_derivation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assistance_titular_id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.String(length=900), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=5), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('social_case_assistance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('derivation_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['derivation_id'], ['social_case_derivation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'intervention_plan', ['id'])
    op.add_column('social_case', sa.Column('derivation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'social_case', 'social_case_derivation', ['derivation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_case', type_='foreignkey')
    op.drop_column('social_case', 'derivation_id')
    op.drop_constraint(None, 'intervention_plan', type_='unique')
    op.drop_table('social_case_assistance')
    op.drop_table('social_case_derivation')
    # ### end Alembic commands ###
